// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvTc5oSv881IKxSn6N7wHvvxMzdtaKx9I',
    appId: '1:279637501803:android:9dc2ac2b81f58d928ace2e',
    messagingSenderId: '279637501803',
    projectId: 'raseen-ffb26',
    storageBucket: 'raseen-ffb26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhM9xezo5H-iCZjz_7V98cBjZv9xIqVAM',
    appId: '1:279637501803:ios:e8ca6d6b349b16648ace2e',
    messagingSenderId: '279637501803',
    projectId: 'raseen-ffb26',
    storageBucket: 'raseen-ffb26.firebasestorage.app',
    androidClientId: '279637501803-20jkjgfsas4nq22314qcn9fp6udjo4j4.apps.googleusercontent.com',
    iosClientId: '279637501803-do5c8nmilnu83j3098lv7n0rqshlrd47.apps.googleusercontent.com',
    iosBundleId: 'com.rasin.rasin',
  );
}
